<?php

# This page shouldn't be accessed directly, but there is no harm if they do. 
# Do not let them view warnings caused from a direct visit to the link.
error_reporting(0);

require '../required/database-functions.php'; # Connection to database & database functions

$data = file_get_contents("php://input"); // Read request data following headers

$decodedData = json_decode($data, true); // Fetch PHP associative array from the data read

# Prevent unnecessary database load if the data is blank
# The data is already checked if blank in javascript prior to fetching, but if it's bypassed, it's checked here too

if ($decodedData["captchaToken"] != ""){ 

    // A captcha token was provided

    // Google API url where to send the data
    $googleAPI = 'https://www.google.com/recaptcha/api/siteverify';

    // The data that is required by the API to confirm if the captcha token was valid
    $apiRequiredData = [
        'secret' => 'secret_key_goes_here', // The secret API key used to utilise the API
        'response' => $decodedData["captchaToken"], // The token generated by the user

    ];

    // The data to be sent
    $dataToSend = [
        'http' => [
            'method'  => 'POST', // Specifying that the data will be sent by POST
            'header' => 'Content-type: application/x-www-form-urlencoded', // Specify the header type
            'content' => http_build_query($apiRequiredData) // Specify the API data to be sent to the server
        ],
    ];

    // Stream context (data container) which will get sent to the API
    $dataToSendContainer  = stream_context_create($dataToSend);

    // Send the data to google API & fetch the result of the validity of the token
    $responseFromGoogle = file_get_contents($googleAPI, false, $dataToSendContainer);

    // Check the response
    if (json_decode($responseFromGoogle, true)["success"] == 1){

        // Successful Captcha

        echo "Success";

    } else {

        echo "Fail"; // Invalid token

    }
}

?>