<?php

session_start(); # Starting the session

require '../required/twig-loader.php'; # Shortcut to load composer, twig & its templates

require '../required/database-functions.php'; # Connection to database & database functions

# First step is to check if there are valid sessions stored - if so, template can be served directly

if (checkSessionStatus() == "Valid") {

    # We have valid account data stored in sessions - render in the logged in template

    echo $twig->render("task-list-template.php", array(

        "websiteName" => $websiteName,
        "username" => $_SESSION["username"],
        "taskList" => fetchTasks($_SESSION["username"],$_SESSION["password"]),
        
    ));

    die(); # Kill The PHP Script since template was served

} else if (checkSessionStatus() == "Invalid") { // Invalid Sessions Are Stored - this link was accessed directly

    # Reset the invalid Sessions
    $_SESSION["username"] = "";
    $_SESSION["password"] = "";

}

# At this stage, it means no sessions were stored - checking if a login was called

if (isset($_POST["fusername_login"]) and isset($_POST["fpassword_login"])){

    // A login was indeed called

    if (isset($_POST["g-recaptcha-response"])){ // Only validate the login if the user did the recaptcha

        // Response is not blank, a token was generated by the recaptcha service. This needs to be verified on validity.

        // Google API url where to send the data
        $googleAPI = 'https://www.google.com/recaptcha/api/siteverify';

        // The data that is required by the API to confirm if the captcha token was valid
        $apiRequiredData = [
            'secret' => '6LcfrQ0sAAAAANfeIlsPx4TInxT2LsYW8uiZHdVs', // The secret API key used to utilise the API
            'response' => $_POST["g-recaptcha-response"], // The token generated by the user

        ];

        // The data to be sent
        $dataToSend = [
            'http' => [
                'method'  => 'POST', // Specifying that the data will be sent by POST
                'header' => 'Content-type: application/x-www-form-urlencoded', // Specify the header type
                'content' => http_build_query($apiRequiredData) // Specify the API data to be sent to the server
            ],
        ];

        // Stream context (data container) which will get sent to the API
        $dataToSendContainer  = stream_context_create($dataToSend);

        // Send the data to google API & fetch the result of the validity of the token
        $responseFromGoogle = file_get_contents($googleAPI, false, $dataToSendContainer);

        // Check the response
        if (json_decode($responseFromGoogle, true)["success"] == 1){

            // Successful Captcha

            # Explode is used to seperate status message from user ID
            # Index 0 = Status
            # Index 1 = UserID (If Valid)

            $receivedAccountStatus = explode("-", checkDatabaseAccount($_POST["fusername_login"], $_POST["fpassword_login"]));

            # Username and password provided for login.

            if ($receivedAccountStatus[0] == "Valid"){

                # Outcome 1 - Username and Password Valid - Login!

                # Save the data to sessions so that the user will stay logged in
                $_SESSION["username"] = $_POST["fusername_login"];
                $_SESSION["password"] = $_POST["fpassword_login"];

                # Perform Render of task-list as logged in user

                echo $twig->render("task-list-template.php", array(

                    "websiteName" => $websiteName,
                    "username" => $_POST["fusername_login"],
                    "taskList" => fetchTasks($_SESSION["username"],$_SESSION["password"])
                
                ));

                die(); # Logged in - kill the PHP script

            } # Other scenarios (Invalid password, etc.. are checked in the signup/login pages, not here)

        }

    }

# At this stage, it means session was not stored and login wasn't called, so proceeding with checking if signup was called

} else if (isset($_POST["fusername_signup"]) and isset($_POST["fpassword_signup"])) {

    // A signup was indeed called

    if (isset($_POST["g-recaptcha-response"])){ // Only validate the signup if the user did the recaptcha

        // Response is not blank, a token was generated by the recaptcha service. This needs to be verified on validity.

        // Google API url where to send the data
        $googleAPI = 'https://www.google.com/recaptcha/api/siteverify';

        // The data that is required by the API to confirm if the captcha token was valid
        $apiRequiredData = [
            'secret' => '6LcfrQ0sAAAAANfeIlsPx4TInxT2LsYW8uiZHdVs', // The secret API key used to utilise the API
            'response' => $_POST["g-recaptcha-response"], // The token generated by the user

        ];

        // The data to be sent
        $dataToSend = [
            'http' => [
                'method'  => 'POST', // Specifying that the data will be sent by POST
                'header' => 'Content-type: application/x-www-form-urlencoded', // Specify the header type
                'content' => http_build_query($apiRequiredData) // Specify the API data to be sent to the server
            ],
        ];

        // Stream context (data container) which will get sent to the API
        $dataToSendContainer  = stream_context_create($dataToSend);

        // Send the data to google API & fetch the result of the validity of the token
        $responseFromGoogle = file_get_contents($googleAPI, false, $dataToSendContainer);

        // Check the response

        if (json_decode($responseFromGoogle, true)["success"] == 1){

            // Successful Captcha

            $receivedAccountStatus = explode("-", checkDatabaseAccount($_POST["fusername_signup"], $_POST["fpassword_signup"]));

            # Username and password provided for signup. Check whether or not there is already an account with that username.
            
            if ($receivedAccountStatus[0] == "InvalidUsername") {

                # Invalid username status means that the username does not exist, so we can proceed

                # Outcome 1 - Username Unique! Create account

                # Save the data to sessions so that the user will stay logged in with this new account
                $_SESSION["username"] = $_POST["fusername_signup"];
                $_SESSION["password"] = $_POST["fpassword_signup"];

                createNewUser($_POST["fusername_signup"],$_POST["fpassword_signup"]);

                # Perform Render of task-list as logged in user

                echo $twig->render("task-list-template.php", array(

                    "websiteName" => $websiteName,
                    "username" => $_POST["fusername_signup"],
                    "taskList" => fetchTasks($_SESSION["username"],$_SESSION["password"])
                
                ));

                die(); # Logged in - kill the PHP script

            } # Other scenarios (Invalid password, etc.. are checked in the signup/login pages, not here)

        }

    }
    
}

# If script is still running here, it means something was invalid and the user did not login or signup+login

require '../required/redirect-to-index.php'; # Redirect to index.php for processing without invalid sessions or direct access

?>